PagerDuty reactor
fastmail/Synergy pull request #151
Opened 2021-08-27 16:04 UTC by mmcclimon

NOTE: this is almost certainly incompatible with the VO reactor. It's possible they might both work at the same time, but I haven't tested it.

This is more or less a direct port of the VictorOps reactor, with the necessary changes for the differences between the two services. It's likely we'll want to improve this somewhat, but this gets us to feature parity. The commit messages have more detail, where necessary.

The most notable thing I _didn't_ port was extra behavior on demaint: that is `demaint /resolve` is no longer a thing, nor is `demaint /noresolve`, which never quite worked right anyway.

2021-09-01 09:34 UTC, Davis-A commented
Sorry i didn't get to this today.  Took most of the day off.  I'll take a look tomorrow :)

2021-09-02 00:55 UTC, Davis-A commented on lib/Synergy/Reactor/PagerDuty.pm
> +      # maint startedAt is unix time * 1000
Comment not applicable for PD

2021-09-04 01:23 UTC, Davis-A requested changes

2021-09-04 01:37 UTC, mmcclimon commented on lib/Synergy/Reactor/PagerDuty.pm
> +  return $self->_pd_request(GET => "/incidents?service_ids[]=$sid&statuses[]=triggered&statuses[]=acknowledged&limit=100")
Not an idiot! Those multi-arg query params are weird.

2021-09-04 07:15 UTC, Davis-A commented on lib/Synergy/Reactor/PagerDuty.pm
> +  return $self->_pd_request(GET => "/incidents?service_ids[]=$sid&statuses[]=triggered&statuses[]=acknowledged&limit=100")
Yeah it's super weird.  I also just remembered, Butch mentioned you can 'snooze' an incident like in VO.  But i have no idea what status they'll have as the docs don't mention it.

2021-09-04 07:17 UTC, Davis-A commented
> The most notable thing I didn't port was extra behavior on demaint: that is demaint /resolve is no longer a thing, nor is demaint /noresolve, which never quite worked right anyway.

I thought about this.  I think the default behaviour to resolve is wrong.  But i am in favour of a /resolve option.  But that can totally be added later.

FYI /noresolve was fixed in #146

2021-09-06 00:55 UTC, mmcclimon commented
> I thought about this. I think the default behaviour to resolve is wrong. But i am in favour of a /resolve option. But that can totally be added later.

@Davis-A `demaint /resolve` isn't really useful, because PagerDuty (and now, actually, VO too) doesn't fire incidents at all during maint, so there's nothing _to_ resolve. The previous behavior resolved everything that fired since start of maint plus 10 minutes, I think, which was also very confusing IMO.

2021-09-06 00:57 UTC, Davis-A commented
Oh ... i was under the impression the alerts still fired they just weren't displayed by the integration any more.  That is ... most annoying.

2021-09-07 13:20 UTC, mmcclimon commented on lib/Synergy/Reactor/PagerDuty.pm
> +      # maint startedAt is unix time * 1000
Good catch, thanks!

2021-09-07 13:22 UTC, mmcclimon commented on lib/Synergy/Reactor/PagerDuty.pm
> +  return $self->_pd_request(GET => "/incidents?service_ids[]=$sid&statuses[]=triggered&statuses[]=acknowledged&limit=100")
https://support.pagerduty.com/docs/editing-incidents#snooze-an-incident implies that snoozing is only available for acknowledged incidents, which makes sense.

2021-09-07 17:48 UTC, mmcclimon commented on lib/Synergy/Reactor/PagerDuty.pm
> +  # XXX is this limit sufficient?
@Davis-A I have added two more commits to deal with this in a more general way, which should be sufficient. Let me know if it's not!

2021-09-08 00:22 UTC, Davis-A approved these changes

2021-09-08 00:22 UTC, Davis-A commented
This looks fantastic.  Thanks for doing this Michael!

2021-09-14 00:03 UTC, merged