Add Synergy::Reactor::LinearNotification - handles triage tasks
fastmail/Synergy pull request #162
Opened 2021-12-27 16:42 UTC by wolfsage

That is, any task created with the configured label will send
a message to the configured slack channel about it

2021-12-27 16:48 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +#  unless ($allowed{$req->address}) {
If we actually get the real remote ip we need to check it here (basically just uncomment this)

2021-12-28 02:10 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +
recently earned your doctorate, eh?

2021-12-28 15:36 UTC, rjbs requested changes

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +with 'Synergy::Role::HTTPEndpoint';
Probably makes no difference, but it's almost always better to pass multiple arguments to `with` rather than to call it twice.  That way it will detect composition conflicts.

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +use JSON 2 qw(encode_json decode_json);
As of 5m ago, Synergy always uses JSON::MaybeXS everywhere.  Please amend.
```suggestion
use JSON::MaybeXS qw(encode_json decode_json);
```

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +  default => '/linear_notification/',
```suggestion
  default => '/linear-notification/',
```

LOW LINE is bad in general, but especially in URLs.

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +);
We absolutely must stop using "triage" to mean the old thing!  Yes, this means renaming hunks of code, updating documentation, and so on.  The alternative is explaining this confusing situation to all new hires forever!

What if, instead, configuration was like this:
```
label_subscriptions => {
  'support blocker' => [ [ slack => 'C1234' ], [ twilio => '16105551212' ] ],
  'printer fire' => [ ... ],
}
```

Then multiple labels could be noticed, sending to multiple targets.  Even if we start off only wanting one!

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +);
This is fine, mayyyybe, but do they guarantee this won't change?  Seems unlikely, they're just hosted in the Google cloud.  Instead:
1. I'd hope their webhooks would include some verifiable data!
2. if not, we could add a mandatory path element that is a GUID and can't be guessed, then register that

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +      _cache_guts     => $self->_linear_shared_cache,
I doubt you need a shared cache, since you're only creating one Linear::Client for the life of the reactor.

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +);
Is this ever used?

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +#  warn Dumper $payload;
noise to be deleted

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +       && grep { lc $_->{name} eq $self->triage_label_name } $payload->{data}->{labels}->@*
Nothing required that the label name was lc, so you should lc it here.  But since I already said "maybe this whole bit should be genericized" I can withhold further comments…

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +            "$TRIAGE_EMOJI New task created for triage by %s in %s: %s (%s)",
in a "subscribe to multiple labels" world, we'd replace "for triage" with "with label X"

if we don't enter that world, we still need to expunge "triage"

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +            "zendesk",
This isn't really a constant, right?

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +        })->catch(sub (@) {
You could just leave off the signature, you know!

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +sub start ($self) {}
Surprised we need this!

2021-12-28 15:36 UTC, rjbs commented on lib/Synergy/Reactor/LinearNotification.pm
> +}
This doesn't make sense to me.  If it never matches, why are we registering a listener at all?  Also, I don't think there's a method with that name.  I think this whole sub is a mistake?

2021-12-28 17:21 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +with 'Synergy::Role::HTTPEndpoint';
Yeah, like half of our reactors do it this way already. Could "fix" them all at some point...

2021-12-28 17:21 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +use JSON 2 qw(encode_json decode_json);
Pff. Fine

2021-12-28 17:22 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +);
This is how they document "how to know it's from us!" Sadly there's no other ... thing (a shared secret, etc). Certainly adding a guid makes it less discoverable, but we should really do both.

2021-12-28 17:23 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +);
Yeah, I mean, a lot of this was copy pasta and I didn't bother renaming everything in the interest of getting it working. But I can, sure.

2021-12-28 17:24 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +            "zendesk",
Will fix

2021-12-28 17:24 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +        })->catch(sub (@) {
Fair. I had had a signature which broke shit so I backed it off to this but will just remove

2021-12-28 17:24 UTC, wolfsage commented on lib/Synergy/Reactor/LinearNotification.pm
> +}
We have to be a listener to be a reactor I think? And in the future the reactor *might* handle some things, so for now this makes it all work without having to think/try too hard. I can document it if that's good enough

2021-12-30 16:41 UTC, wolfsage commented
Updated to cover most things - also will now notify if someone adds the label to an existing ticket

2022-01-03 19:43 UTC, rjbs approved these changes

2022-01-04 14:01 UTC, merged