Draft: Linear: make synergy respond to issue identifiers
fastmail/Synergy pull request #168
Opened 2022-01-03 21:37 UTC by RashaMou

In slack, any mention of an issue id expands to show information about
that issue and a link

2022-01-13 15:38 UTC, RashaMou commented
@rjbs this is almost ready, but we need to merge the [issue lookup PR](https://github.com/fastmail/Linearsonist/pull/23) in Linearsonist to complete it.

2022-01-19 17:20 UTC, rjbs requested changes

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      exclusive => 1,
Can't be targeted or it'll only fire when someone says "Synergy: BAK-123".  Can't be exclusive or you can't say "++ fix the second problem seen in BAK-321"

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      $linear->fetch_issue($issue_id)->then(sub ($issue) {
this is 4 sp instead of 2 sp indents

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    $issue->{team}."-".$issue->{number};
You could use $issue->{identifier} instead, which is already in the form XYX-123.

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  $event->mark_handled if $event->was_targeted;
(Oh, I should make this a generic facility of CommandPost!  For now, keep this line…)

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      $linear->fetch_issue($issue_id)->then(sub ($issue) {
You don't have any handling for bogus issues.  What if I say "This will be fixed in BAK-1232134123"?  That issue won't exist and I can't tell what will happen here!

2022-01-19 17:20 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      $linear->fetch_issue($issue_id)->then(sub ($issue) {
With changes suggested in L-C, $issue would now be undef, so you would want to:
* if targeted, reply_error "no such issue, dawg"
* if not targeted, just return done

2022-01-19 20:20 UTC, RashaMou commented on lib/Synergy/Reactor/Linear.pm
> +      $linear->fetch_issue($issue_id)->then(sub ($issue) {
I made this change, but could use double checking to make sure I understood correctly.

2022-01-26 20:00 UTC, rjbs commented
I will rebase this on the CommandPost changes and apply, thanks!

2022-01-27 02:44 UTC, rjbs requested changes
I have rebased this, as promised, on the commandpost-extra branch.  I'll walk you through my changes tomororw.

2022-01-27 02:44 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +        return $event->reply("$link: $title");
The Slack formatted link has to be given as an "alternative" display, because you don't want to SMS somebody something like `<http:/...foo../|Foo 123>`.  You want:
```
$event->reply($plaintext, { alt_type => $value, alt_type_2 => $value_2, ... });
```

2022-01-27 02:45 UTC, closed without merging