DiagnosticUplink: add a network diagnostic interface
fastmail/Synergy pull request #171
Opened 2022-01-10 00:39 UTC by rjbs

I have future plans for this, like making a role like HasDiagnosticInterface for reactors.  But for now, this goes a long way.

2022-01-10 19:37 UTC, wolfsage requested changes

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/DiagnosticUplink.pm
> +
Without `$line =~ s/\r$//;` this doesn't work for me since \r is included

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/TextThemer.pm
> +  $self->$method($what->@[ 1 .. $what->$#* ]);
This crashes (in some cases?) because it calls, say, 'format_notice' without a `$from` if used on the console:
```
/format test
Too few arguments for subroutine 'Synergy::TextThemer::_format_notice' (got 2; expected 3) at lib/Synergy/TextThemer.pm line 207.
	Synergy::TextThemer::_format_notice(Synergy::TextThemer=HASH(0x56112dd9b968), "Not a valid message format.") called at lib/Synergy/TextThemer.pm line 207
	Synergy::TextThemer::_format(Synergy::TextThemer=HASH(0x56112dd9b968), ARRAY(0x56112de13be0)) called at inline delegation in Synergy::DiagnosticHandler for theme->_format (attribute declared in lib/Synergy/DiagnosticHandler.pm at line 53) line 18
	Synergy::DiagnosticHandler::_format(Synergy::Channel::Console::DiagnosticHandler=HASH(0x56112dd9b8f0), ARRAY(0x56112de13be0)) called at lib/Synergy/DiagnosticHandler.pm line 300
	Synergy::DiagnosticHandler::_do_diagnostic_command(Synergy::Channel::Console::DiagnosticHandler=HASH(0x56112dd9b8f0), "/format test") called at inline delegation in Synergy::Channel::Console for _diagnostic_handler->_do_diagnostic_command (attribute declared in lib/Synergy/Channel/Console.pm at line 326) line 18
```

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/TextThemer.pm
> +  $self->$method($what->@[ 1 .. $what->$#* ]);
Even `/format chonky` fails for me. It tries to say "updated." but again doesn't have a `$from`

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/DiagnosticUplink.pm
> +
Cute!

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/DiagnosticHandler.pm
> +  /eval     - evaluate a Perl string, if enabled; $S refers to the hub
`/eval exit && print "oh no"`

2022-01-10 19:37 UTC, wolfsage commented on lib/Synergy/Channel/Console.pm
> +channel with Synergy.  If you sent text that doesn't start with a slash, it
s/sent/send/

2022-01-10 19:38 UTC, wolfsage commented
I like the general idea. At least for me though, a few things don't seem to work?

2022-01-10 20:14 UTC, rjbs commented on lib/Synergy/TextThemer.pm
> +  while (my $line = shift @lines) {
Fixed, thanks.

2022-01-10 20:14 UTC, rjbs commented on lib/Synergy/Channel/Console.pm
> +      color_scheme => $self->color_scheme,
Funny, I meant to put in the right code for this but did not.

2022-01-10 20:16 UTC, rjbs commented on lib/Synergy/DiagnosticUplink.pm
> +
Could you try with \R instead of \n there?

2022-01-11 02:21 UTC, rjbs commented on lib/Synergy/TextThemer.pm
> +  $self->$method($what->@[ 1 .. $what->$#* ]);
Thanks, fixed.

2022-01-11 02:21 UTC, rjbs commented on lib/Synergy/DiagnosticUplink.pm
> +
:)

2022-01-11 02:22 UTC, rjbs commented on lib/Synergy/DiagnosticHandler.pm
> +  /eval     - evaluate a Perl string, if enabled; $S refers to the hub
Yeah, I thought about using Safe and maybe later I will, but… this is a powerful and dangerous tool :)

2022-01-11 02:22 UTC, rjbs commented on lib/Synergy/Channel/Console.pm
> +channel with Synergy.  If you sent text that doesn't start with a slash, it
Thanks, fixed.

2022-01-11 02:23 UTC, rjbs commented
@wolfsage I think this is all fixed except for the \n thing which I want your input on more.

2022-01-11 13:48 UTC, wolfsage commented on lib/Synergy/DiagnosticUplink.pm
> +
Turns out you need: `while ($$buffref =~ s/^(.*?)\R//) {` since \R can match 1 or 2. Also if you do this you can drop the chomp since the newline will be outside `$1`.

2022-01-11 13:53 UTC, wolfsage commented
I've suggested fix for the `\R` issue you mentioned (but not in like a github fix suggestion way).

Also, on the diagnostics port and normal console, /help lists nlist and ntree, but no entries exist in the help for those.

Also on the diagnostics port no help hint is show in /help for eval, but /help eval works. (Same on console really - /help eval works)

2022-01-11 19:19 UTC, rjbs commented
Raw /help points to /help diag, which includes mention of eval, so I didn't add more.  I did add help for nlist and ntree.

2022-01-11 19:26 UTC, merged