Linear: Add DedpuplicatesExpando to Linear reactor
fastmail/Synergy pull request #178
Opened 2022-02-03 17:41 UTC by RashaMou

2022-02-09 18:23 UTC, RashaMou commented
@mmcclimon can you give this a look please?

2022-02-11 14:59 UTC, mmcclimon requested changes
Mostly ok but a few comments!

2022-02-11 14:59 UTC, mmcclimon commented on lib/Synergy/Reactor/Linear.pm
> +    if ($self->has_expanded_issue_recently($event, $_)) {
You need one other bit in this MR for this to work correctly, which it to call `$self->note_issue_expansion($id)` when you actually expand one, so that we know we've expanded it recently!

2022-02-11 14:59 UTC, mmcclimon commented on lib/Synergy/Reactor/Linear.pm
> +  for (@matches) {
Also, I would move this block down below the part where you canonicalize `@matches` (uniq and uc them). That's to avoid a problem like:

1. Someone says "bak-42"
2. We hit this block, there's no expansion key for it
3. Below, we uppercase it, expand it, then note expansion for "BAK-42"
4. goto 1.

2022-02-11 19:06 UTC, RashaMou commented
thanks! made the changes, back to you!

2022-02-28 18:21 UTC, RashaMou commented
@mmcclimon just bumping this up!

2022-02-28 19:58 UTC, mmcclimon commented
I applied this after rebasing, thanks!

2022-02-28 19:58 UTC, closed without merging