Linear Reactor: comment on Linear issues
fastmail/Synergy pull request #190
Opened 2022-10-06 20:38 UTC by RashaMou

Synergy will react to "comment on plu-xxx: comment" by adding a comment to the given issue

2022-10-07 17:31 UTC, RashaMou commented
@rjbs synergy comment code ready for review

2022-10-07 18:35 UTC, rjbs requested changes

2022-10-07 18:35 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      } else {
"Never write `else` blocks." 🙂

The previous `if` will have returned, so no need for else.

2022-10-07 18:35 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +responder new_comment => {
This should be a command, not a responder.

2022-10-07 18:35 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  $event->mark_handled;
You don't need mark_handled if the caller is a command instead of a responder.

2022-10-07 19:42 UTC, RashaMou commented on lib/Synergy/Reactor/Linear.pm
> +      } else {
noted, but also this whole sub is gone now \o/

2022-10-07 19:42 UTC, RashaMou commented on lib/Synergy/Reactor/Linear.pm
> +responder new_comment => {
changed to a command - so much better!

2022-10-07 20:19 UTC, rjbs requested changes
A few small things, but very close!

2022-10-07 20:19 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  aliases => ["comment on"],
This doesn't make sense as an alias to me.  Comment matches the first word.  The "on" is in $rest.

2022-10-07 20:19 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  my ($issue, $comment) = $rest =~ /\s+(.*-\d*)+:?(.*)/;
This should be anchored at both ends, probably, and should account for "on"`

2022-10-07 20:19 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  return unless $issue && $comment;
At this point, in a command, we have committed to handling this command.  We must not just return, but should provide an error message instead.

2022-10-07 20:19 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    my $issue_id_f = $linear->fetch_issue($issue);
This is fetching an issue, not an issue id. You are passing it an issue identifier.  We should put the identifier in $issue_ident, then pass that in, then store the future in $issue_f.

This is a bit nit-picky, sorry, but it's important:  Without a real type system, we have to rely on the variable names to tell us what's what.

2022-10-07 20:19 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    $issue_id_f->then(sub ($id) {
…and then $id here is $issue.  If you call it $id and then say $id->{id} some future reader's head will explode! 😄

2022-10-10 01:21 UTC, rjbs requested changes
Very close, mostly a change for you to review and apply, 1-2 small nits.  Deploy Monday?

Also, I think you need to add some vertical whitespace between paragraphs and maybe wrap some long lines.

I am going to use the hell out of this feature.

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  my ($issue_ident, $comment) = $rest =~ /^(?:on\s)?(.*-\d*)+:?(.*)\z/;
```suggestion
  my ($issue_ident, $comment) = $rest =~ /
    ^
    (?:on\s+)?
    ([a-z]+-[0-9]*)
    :?
    \s+
    (.*)
    \z
  /ix;
```

Lots of tiny changes made here:

1. use /x to allow newlines and space in the regex so it's more readable
2. put `+` after the space after "on" so you can say `on    CLI-123` if you hit space too long
3. replaced `.*` in the left hand side of the CLI-123 matcher with `[a-z]+` — .* is exceptionally greedy; remember that `.` would match `:` and all kinds of weird things could be parsed weird
4. replaced `\d` with `[0-9]` — this is a pet peeve of mine.  \d matches lots of things you don't want.  I have annoyingly included a small sample below
5. added `\s+` to go between issue identifier and comment so you can't say `comment cli-123it's done`

Sorry for doing "here's just code" but these are all small but worth doing, and the Socratic method was probably going to be really obnoxious here!

```
 ๖  U+0E56 THAI DIGIT SIX
 ໖  U+0ED6 LAO DIGIT SIX
 ༦  U+0F26 TIBETAN DIGIT SIX
 ၆  U+1046 MYANMAR DIGIT SIX
 ႖  U+1096 MYANMAR SHAN DIGIT SIX
 ៦  U+17E6 KHMER DIGIT SIX
 ᠖  U+1816 MONGOLIAN DIGIT SIX
 ᥌  U+194C LIMBU DIGIT SIX
 ᧖  U+19D6 NEW TAI LUE DIGIT SIX
 ᪆  U+1A86 TAI THAM HORA DIGIT SIX
```

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  $comment=~ s/^\s+//;
This line not needed with the regex change above.

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  $self->_with_linear_client($event, sub ($linear) {
I have a branch now where I async/await all of the Linear reactor, and it's so nice.  We'll do this routine after I merge my branch.  I think you will be pleased.

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +        $event->reply($comment_id);
This seems like debugging noise left over.  No human wants this information. 🙂

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +          return $event->reply($text, { slack => $text });
Here, you're sending Slack-formatted text (the `<link|text>`) to plaintext channels like SMS.  You should have two different strings to send: one plain, one Slack.

2022-10-10 01:21 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +        return $event->error_reply("Sorry, something went wrong and I can't say what!");
In this case, you should $Logger log the $res, so the logs show what happened.

2022-10-12 15:50 UTC, RashaMou commented on lib/Synergy/Reactor/Linear.pm
> +  $self->_with_linear_client($event, sub ($linear) {
ooo yes! excited for that.

2022-10-12 16:10 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +        $Logger->log("Err: $res");
```suggestion
        $Logger->log("error trying to create a comment on $issue_ident: $res");
```

2022-10-12 16:10 UTC, rjbs approved these changes

2022-10-12 16:14 UTC, merged