Add a very basic 'search ...' to Linear Reactor
fastmail/Synergy pull request #197
Opened 2023-06-02 19:56 UTC by wolfsage

This searches tickets and comments in the same way the UI does when using the Advanced Search interface

2023-06-02 20:11 UTC, wolfsage commented
This code was very much "get it working while under duress" so there's definitely some stuff that could be refactored / written more cleanly. If any of it bothers you enough let me know :)

2023-06-02 20:25 UTC, wolfsage commented
The bolding stuff doesn't work if we're trying to bold a username because it becomes `@*alh*` which slack does nothing with. I can maybe work around that...

2023-06-02 20:28 UTC, wolfsage commented
Maybe could use https://api.slack.com/messaging/composing/layouts#stack_of_blocks text blocks with 'verbatim' and 'mrkdwn' types to mix/compose the output. Ugh

2023-06-02 20:29 UTC, rjbs commented
Pretty sure the blocks will become, like, *blocks*.  So, breaks between them.  No good for inline formatting.

2023-06-02 20:50 UTC, rjbs requested changes
Looks pretty good!

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +use POSIX qw(ceil);
I hate that this is in POSIX.  But that isn't your fault.

As far as I know.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      * /closed: Include tasks in the canceled/completed states
```suggestion
    • TEXT: The string(s) to search
    • /page N: Which page of results to retrieve, if there's more than 1
    • /count N: Return N results. Default is 10. Any more will be a private response
    • /closed: Include tasks in the canceled/completed states
```

This suggestion matches formatting with other help lists in Linear reactor, like "new_issue"

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  if ($rest =~ s{\s/page\s+(\d+)}{}i) {
I know, I know, but:  you should put `/a` on these, because you don't want somebody to say `/pages ६` and cause some unhandled error.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  if ($rest =~ s{\s/page\s+(\d+)}{}i) {
Also do you want `\s*` after the captured digit string?  I think you might.  But maybe it doesn't matter in the final analysis.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  }
Often for this kind of code, we use `_with_linear_client` — maybe you want to use that here.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    }
Ugh, I'm sorry that you had to write this.  It's my fault.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    my $query = "query {\n" . $selection->as_string("  ") . "\n}\n";
I believe you want:
```
select => [
  totalCount =>
  pageInfo => { ... },
  nodes => { ... }
]
```

That is:  I believe it takes an optlist (a la Data::OptList).

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  my $xtract  = sub { $_[0]{data}{searchIssues} };
I'd use a signature.

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    $query_result = await $query_result->next_page;
Probably the polite way to do this is something else, like embed a link in the message that triggers Synergy to fetch the second page by re-providing the stored cursor…

…but this should be fine unless we get rate limited from people saying page:4

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +  my $text = my $slack = "*Your results for $rest...*\n";
```suggestion
  my $text = my $slack = "*Your results for «$rest»:*\n";
```

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +    PATH: for my $path ([qw(title)], [qw(comment body)], [qw(description)]) {
Cute. :)

2023-06-02 20:50 UTC, rjbs commented on lib/Synergy/Reactor/Linear.pm
> +      warn Dumper $node;
This should probably use $Logger.

2023-06-04 20:54 UTC, wolfsage reviewed
Updated a bunch and cleaned up. This needs https://github.com/fastmail/Linear-Client/pull/37 and also Feature::Compat::Defer (just for debugging... so we could remove that bit if we want)

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +    $query_result = await $query_result->next_page;
The rate limiting is pretty generous and done by points usage. Each page for a simple query is about 8 points, and you get 250,000 an hour, I think we're good

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +    PATH: for my $path ([qw(title)], [qw(comment body)], [qw(description)]) {
:)

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +      * /closed: Include tasks in the canceled/completed states
Fixed

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +  }
Fixed (Half the code in hear does what I was doing which is where I got it from :))

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +    }
I didn't! I copied this mostly from elsewhere. And now I've undone it all because it turns out I can just us do_paginated_query!

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +    my $query = "query {\n" . $selection->as_string("  ") . "\n}\n";
Fixed (requires https://github.com/fastmail/Linear-Client/pull/37)

2023-06-04 20:54 UTC, wolfsage commented on lib/Synergy/Reactor/Linear.pm
> +      warn Dumper $node;
Fixed

2023-06-04 20:55 UTC, wolfsage commented
Will squash all commits before merging since history is a mess

2023-06-09 16:51 UTC, rjbs commented
@wolfsage I pushed a commit to update prereqs.  I merged and installed the new client on synergy.  I installed defer there too.

Branch looks good, ship it.

2023-06-13 12:28 UTC, merged