Zendesk reactor: skip getting zendesk tickets if user has no zendesk account
fastmail/Synergy pull request #201
Opened 2023-07-11 17:26 UTC by RashaMou

@wolfsage I am not sure how to test this locally.

2023-07-13 20:05 UTC, RashaMou commented
@wolfsage this is ready for review

2023-08-14 14:14 UTC, wolfsage commented
This should log if we don't find a user, and also log if there's some kind of exception. This way we can see why reports might not fire for a user and not have to guess

2023-08-24 16:39 UTC, wolfsage requested changes

2023-08-24 17:56 UTC, RashaMou commented on lib/Synergy/Reactor/Zendesk.pm
> +  unless ($user_ok) {
yes, it does, thanks

2023-08-28 17:44 UTC, wolfsage commented on lib/Synergy/Reactor/Zendesk.pm
> +                      ->$user
This change makes no sense. Really what you'd do at this point is `$res = $user->scoped_client->make_request_f...` probably. Maybe we pair on this this week and do it live on synergy and see what happens :)

2023-08-28 18:46 UTC, RashaMou commented on lib/Synergy/Reactor/Zendesk.pm
> +                      ->$user
Yeah that would be great, there's something I'm not quite getting here!

2023-08-31 15:37 UTC, merged