Inabox setup snippet
fastmail/Synergy pull request #212
Opened 2023-11-03 03:31 UTC by Davis-A

I really dislike getting a raw text file reply when something goes wrong!

2023-11-03 06:02 UTC, Davis-A commented on lib/Synergy/Reactor/InABox.pm
> +async sub _post_gitlab_snippet ($self, $payload) {
This could (should?) be moved to the Gitlab reactor and made public so other reactors can call into it.

2023-11-03 17:59 UTC, rjbs commented
I've made some comments.  It took me a moment to realize that the behavior is:
* if GitLab, use that
* if not, and if current channel is Slack, use Slack snippet
* failing that, just use a normal reply

I think you should add a comment to that effect, and you can drop the comment that just says "post a GitLab snippet", since the code is clear.

2023-11-03 17:59 UTC, rjbs requested changes

2023-11-03 17:59 UTC, rjbs commented on lib/Synergy/Reactor/GitLab.pm
> +    die "error creating snippet on gitlab " . $res->as_string;
```suggestion
    die "error creating snippet on GitLab: " . $res->as_string;
```

2023-11-03 17:59 UTC, rjbs commented on lib/Synergy/Reactor/GitLab.pm
> +  my $json = $res->decoded_content(charset => 'undef');
undef should not be quoted, it is a keyword:

```suggestion
  my $json = $res->decoded_content(charset => undef);
```

It's used here to say that no charset decoding should be performed, only decompression.

2023-11-03 17:59 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +  if ($self->hub->reactor_named('gitlab')) {
The reactor name to use should be a configuration option.

2023-11-03 17:59 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +    $payload->{file_name} = "In-a-Box-setup-failure-$droplet->{name}-$username.txt";
Won't the username already be in the droplet name?  (I think so, but am not sure.)

2023-11-03 17:59 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +    my $payload;
It's a nit, but I would suggest `my %payload`.  Then you can drop a bunch of `->` operators.  This is more efficient, but not importantly so.  On the other hand, it is easier to read.  Then later, to pass a reference, you can just replace `$payload` with `\%payload`.

2023-11-03 21:18 UTC, Davis-A commented on lib/Synergy/Reactor/GitLab.pm
> +  my $json = $res->decoded_content(charset => 'undef');
I'll note that I cribbed that handling from Dobby/Client.pm, so that bug exists there in two places then: 

https://github.com/fastmail/Synergy/blob/main/lib/Dobby/Client.pm#L66
https://github.com/fastmail/Synergy/blob/main/lib/Dobby/Client.pm#L86

2023-11-03 22:22 UTC, rjbs commented on lib/Synergy/Reactor/GitLab.pm
> +  my $json = $res->decoded_content(charset => 'undef');
WOW.  What on earth did I do there?  Thanks, I'll fix it.

2023-11-03 22:38 UTC, rjbs commented
I meant to add:  The commit messages do not match the usual style, in which almost all commits begin with the reactor or channel name _exactly_, meaning with matching case.

2023-11-04 01:28 UTC, Davis-A commented
Thanks for the extremely thorough review!  I think fixed everything requested

2023-11-04 14:31 UTC, rjbs commented
Oho!  So, your commit https://github.com/fastmail/Synergy/pull/212/commits/283c8478f5034b7dcdaf16aca2acec73adb17497 is a good fix, as it eliminates a weird never-happens case.  You're fixing my bug, but you're fixing it not the way I intended.  (How could you know??)

My intent was that the snippet would always be posted, so that you could always see what happened, just in case.  You can take 120s and think about whether that's a better idea.  I'm just not sure.

Anyway, this all looks good!  Thanks for the improvements.

2023-11-04 14:32 UTC, rjbs approved these changes

2023-11-07 21:42 UTC, Davis-A commented
> My intent was that the snippet would always be posted, so that you could always see what happened, just in case

I'm pretty happy only getting it if it fails.  For now i'll merge this, if you really want it to be all the time throw me a task and chuck the Fryday label on it and i'll do it soon.

2023-11-07 21:42 UTC, merged