InABox: Check snapshot regions before creating box
fastmail/Synergy pull request #222
Opened 2024-02-09 01:57 UTC by Davis-A

When a snapshot is unavailable in the users datacentre it's much nicer to reply with a better response than "Something weird happened..."

2024-02-09 01:57 UTC, Davis-A commented
The functionality is there.  But i need to update the test suite before merging.

2024-02-09 02:27 UTC, Davis-A commented
Tests fixed so i think this is good to go

2024-02-09 13:19 UTC, wolfsage commented on lib/Synergy/Reactor/InABox.pm
> +        "Unable to create snapshot in region '$region.  Available compatible regions are $compatible_regions."
nit: missing closing quote after `'$region`

Same below

2024-02-09 13:21 UTC, wolfsage commented
Nice, though you aren't testing for the new error conditions? Would be nice to!

2024-02-12 19:31 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +        "Unable to create snapshot in region '$region.  Available compatible regions are $compatible_regions."
(yup)

2024-02-12 19:42 UTC, rjbs requested changes
You're going to have to change this when you rebase after the big test improvements, but it should be easy.

But also, I thing you've got more API requests than are needed for this?  And testing the failure mode is probably a good idea, as Matthew said.

2024-02-12 19:42 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +    await $self->_get_snapshot_regions($snapshot->{id});
This seems off to me.  Above, with this line…

```perl
my $snapshot = await $self->_get_snapshot($version);
```

…it seems like we should have a snapshot already retrieved.  Then, `_get_snapshot_regions` goes and fetches it again.  Meanwhile, the API reference suggests that the objects returned from `_get_snapshot` should *already* have the region data.  That would mean that this branch is adding another round trip and another place for things to fail.

Can you, instead, look at `$snapshot->{regions}` without making another request?

2024-02-12 21:44 UTC, Davis-A commented on lib/Synergy/Reactor/InABox.pm
> +    await $self->_get_snapshot_regions($snapshot->{id});
I am indeed an idiot.  For some reason my brain decided that `$snapshot` was just an id, but clearly it's a hash because i'm getting the id from it 🤦

2024-02-12 22:00 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +    await $self->_get_snapshot_regions($snapshot->{id});
If this is the worst mistake you make all week, you'll be doing great. 😄

2024-02-13 00:12 UTC, Davis-A commented
Okie dokie.  Re-done without my 🤦 error.

Also added tests for the snapshot check too.

```
adavis@carbon:~/src/Synergy$ yath t/inabox.t

** Defaulting to the 'test' command **

( PASSED )  job  1    t/inabox.t

                                Yath Result Summary
-----------------------------------------------------------------------------------
     File Count: 1
Assertion Count: 33
      Wall Time: 3.28 seconds
       CPU Time: 3.69 seconds (usr: 0.12s | sys: 0.04s | cusr: 2.99s | csys: 0.54s)
      CPU Usage: 112%
    -->  Result: PASSED  <--
```

2024-02-13 00:23 UTC, rjbs approved these changes
Love it.

2024-02-13 00:42 UTC, merged