InABox: Add support for /region alias for /datacentre
fastmail/Synergy pull request #236
Opened 2024-06-27 03:27 UTC by lerlacher-fm

I always type "/region" on the first try because I've spent too much time in the cloud so region is the natural concept in my head rather than datacentre. So let's make the robot accomodate the human.

2024-06-27 14:20 UTC, wolfsage commented on lib/Synergy/Reactor/InABox.pm
> +  if (!exists $switches{datacentre}) {
I think the end goal here is that datacentre, datacenter, and region all mean the same thing, and providing more than 1 of them is a mistake. I think we can simplify this greatly with:
```
  my @got = grep { exists $switches{$_} } qw(datacenter datacentre region);

  if (@got > 1) {
    die "The following options are mutually exclusive: @got\n";
  }

  $switches{datacentre} = delete $switches{$got[0]};
```

Thoughts?

2024-06-27 22:53 UTC, lerlacher-fm commented on lib/Synergy/Reactor/InABox.pm
> +  if (!exists $switches{datacentre}) {
Yes, that looks much cleaner! Let me test if this works in all cases.

2024-06-28 00:32 UTC, lerlacher-fm commented on lib/Synergy/Reactor/InABox.pm
> +  if (!exists $switches{datacentre}) {
I have tested this and slightly adjusted it to make it all work nicely.

2024-07-01 18:25 UTC, rjbs requested changes

2024-07-01 18:25 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +  my @got = grep { exists $switches{$_} } qw(datacenter datacentre region);
See that comment of mine you're deleting?  About a more generic switch normalizer?  We have one now!  Actually, weirdly, we had one then.  I'm not sure why I didn't use it.  Maybe because it doesn't validate, but it *does* normalize.

You should import `canonicalize_names` from String::Switches at the top of this file.  Then you can write, above the `my %switches = map …` line:

```perl
canonicalize_names($switches, {
  datacenter => 'datacentre',
  region => 'datacentre'
});
```

(As a side note, our policy is to use the American English spelling for code and variables, but changing that will take a bit more work here, so let's let it slide for now.

2024-07-01 18:25 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +
bogus extra space

2024-07-01 18:25 UTC, rjbs commented on lib/Synergy/Reactor/InABox.pm
> +    $switches{datacentre} = delete $switches{$got[0]};
This won't be needed if you use the canonicalizer.  (The last switch will just win, but if we want to fix that, we fix it in the `map` statement, not here.  That will fix it for every switch.)

2024-07-12 02:08 UTC, lerlacher-fm commented
@rjbs I have applied your suggestions, rebased, and gave it a very rudimentary test-drive.

2024-07-12 02:10 UTC, rjbs commented
@lerlacher-fm Thanks for humoring me, change looks good (and did indeed drop some complexity imho). 👍🏽

2024-07-12 02:10 UTC, rjbs approved these changes

2025-04-15 00:11 UTC, merged